### ISSUE TITLE
waterfurnace.waterfurnace.WFWebsocketClosedError

### ISSUE THREAD

**Issue by mdallaire** [sdague/waterfurnace#1]
* waterfurnace version: 7.0
* Python version: 3.6
* Operating System: Docker image : homeassistant/home-assistant

### Description

I have a freshly installed geothermal pump with Aurora weblink linked to Symphony that I am trying to use with Home-Assistant.  The Symphony website works correctly outside of Home-Assistant.

### What I Did

After configuring the component I get the following:
```


`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/waterfurnace/waterfurnace.py", line 164, in read
    datadecoded = json.loads(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-11-07 10:46:27 ERROR (Thread-2) [homeassistant.components.waterfurnace] Failed to read data, attempting to recover
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/waterfurnace/waterfurnace.py", line 164, in read
    datadecoded = json.loads(data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/homeassistant/components/waterfurnace.py", line 149, in run
    self.data = self.client.read()
  File "/usr/local/lib/python3.6/site-packages/waterfurnace/waterfurnace.py", line 174, in read
    raise WFWebsocketClosedError()
waterfurnace.waterfurnace.WFWebsocketClosedError

```
https://github.com/home-assistant/home-assistant/issues/18306

**Comment by mdallaire** [comment]
All working now thanks!
